### ISSUE TITLE
async=True giving error

### ISSUE THREAD

**Issue by ashuein** [PabloEnmanuelRamos/BioBlender21#6]
While trying to load BioBlender addon on Blender 2.91 it gives error:

`fake_module: addon missing 'bl_info' gives bad performance!: '~/.config/blender/2.91/scripts/addons/BioBlender2.py'
Traceback (most recent call last):
  File "/snap/blender/51/2.91/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "~/.config/blender/2.91/scripts/addons/BioBlender/__init__.py", line 38, in <module>
    from .BB2_GUI_PDB_IMPORT import *
  File "~/.config/blender/2.91/scripts/addons/BioBlender/BB2_GUI_PDB_IMPORT.py", line 28, in <module>
    from . import BB2_PANEL_VIEW as panel
  File "~/.config/blender/2.91/scripts/addons/BioBlender/BB2_PANEL_VIEW.py", line 423
    if async:
           ^
SyntaxError: invalid syntax
`

I think this is happening as `async` is a reserved word from Python 3.7 onwards. I installed blender using the command

`sudo snap install blender --classic`   and upon starting blender it mentions the following:

`found bundled python: /snap/blender/51/2.91/python`

Any suggestion on what to do?

**Comment by PabloEnmanuelRamos** [comment]
Hi.  This error happens to you because async is a reserved word as of python 3.7.  However, this version of Bioblender works only up to Blender 2.79b.  I think you are using Blender 2.91, therefore it is going to give an error in any case, since many changes were made from Blender 2.8 onwards.  We are still in the process of a fully working version for these new versions of Blender.  On the official BioBlender page http://www.bioblender.org/ you will be able to download a more advanced version of BioBlender, which works in these new versions of Blender. 

If you want to write me directly to my email I can make some suggestions, since all the BioBlender functions are still in development for these new versions of Blender, and therefore, I have a more advanced version of BioBlender that has not yet been officially uploaded.
pabloerb@estudiantes.uci.cu

Regards

**Comment by ashuein** [comment]
Dear Pablo,

First of all, I would like to thank and appreciate your prompt response and
coming forward to help me out. I realized that this is the problem with the
blender version compatibility.
Please let me know what I need to do if I wish to work with the latest
version of BioBlender in Blender 2.91?



Thanks

Sincerely

Ashutosh Kumar Pandey

Research Associate
School of Biological Sciences
Indian Institute of Technology, New Delhi

**Comment by PabloEnmanuelRamos** [comment]
Dear Ashutosh,

Honestly, the version that is currently working mostly is the version found here on Github.  What happens is that this version works in Blender 2.79b, with python 3.5.  But if you want to work with a more modern Blender, you can work with the new versions of Bioblender, which is currently under development, therefore, some functions do not work as they should.  For example, the electrostatic potential does not render the lines and therefore the images do not show them, we have already solved this problem but not completely, since we are trying to improve it, to show more realistic lines.  If you want this new version write to my email, so I can communicate privately with you  and be able to send you the most advanced version of Bioblender by any means.  

Regards

**Comment by ashuein** [comment]
Dear Pablo,

Given the issues that are still being addressed by you, I would wait for it
to be officially released. In the meantime, I will install the Blender
2.79b version and corresponding BioBlender version in a  virtual box and
work with it. Thanks for the assistance.

Thanks

Sincerely

Ashutosh Kumar Pandey

Research Associate
School of Biological Sciences
Indian Institute of Technology, New Delhi
